#ifndef CALENDARIZADOR_CONSTANTS_H
#define CALENDARIZADOR_CONSTANTS_H


#define LIFE_TIME_IMMORTAL -1
#define LIFE_TIME_STANDARD 20 //s


//#define TIME_FIX_FACTOR 20
#define TIME_FIX_FACTOR 0


#define FISHER_BOAT_SPEED_MULTIPLIER 1.5
#define PATROL_BOAT_SPEED_MULTIPLIER 2


//Direction
#define RIGHT 0
#define LEFT 1

// Quantum
#define QUANTUM_TIME 1

// Boat priority
//#define NORMAL_BOAT_PRIORITY 0
//#define FISHING_BOAT_PRIORITY 1
//#define PATROL_BOAT_PRIORITY 2


#endif //CALENDARIZADOR_CONSTANTS_H
