#ifndef CALENDARIZADOR_CONSTANTS_H
#define CALENDARIZADOR_CONSTANTS_H


#define LIFE_TIME_IMMORTAL -1
#define LIFE_TIME_STANDARD 20 //s


//#define TIME_FIX_FACTOR 20
#define TIME_FIX_FACTOR 0


#define FISHER_BOAT_SPEED_MULTIPLIER 1.5
#define PATROL_BOAT_SPEED_MULTIPLIER 2


//Direction
#define RIGHT 0
#define LEFT 1

#endif //CALENDARIZADOR_CONSTANTS_H
