name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
#      - name: Configure gtk
#        run: |
#          sudo apt-get install libgtk-3-dev
      - name: Build CEThreads
        run: |
          cd CEThreads
          mkdir build
          cd build
          cmake ../
          cmake --build .
      - name: Build canal
        run: |
          cd canal
          mkdir build
          cd build
          cmake ../
          cmake --build .
      - name: Build hw_iface
        run: |
          cd hw_iface
          mkdir build
          cd build
          cmake ../
          cmake --build .
      - name: Build sw_iface
        run: |
          cd sw_iface
          mkdir build
          cd build
          cmake ../
          cmake --build .
      - name: Build calendarizadores
        run: |
          cd calendarizadores
          mkdir build
          cd build
          cmake ../
          cmake --build .
#  test:
#    runs-on: ubuntu-latest
#    steps: 
#      - name: Checkout
#        uses: actions/checkout@v2
#        with:
#          submodules: 'true'
#      - name: Test Common
#        run: |
#          cd test/unit_tests/common
#          mkdir build
#          cd build
#          cmake ..
#          make
#          ./linked_list_on_shared_memory_test
